/**************************************************************************//**
 * @file     SAM3S.h
 * @brief    CMSIS Cortex-M3 Device Peripheral Access Layer Header File
 *           for the Atmel SAM3S Device Series
 * @version  V1.00
 * @date     13. November 2009
 *
 * @note
 * Copyright (C) 2009 ARM Limited. All rights reserved.
 *
 * @par
 * ARM Limited (ARM) is supplying this software for use with Cortex-M 
 * processor based microcontrollers.  This file can be freely distributed 
 * within development tools that are supporting such ARM based processors. 
 *
 * @par
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED
 * OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * ARM SHALL NOT, IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 ******************************************************************************/


#ifndef __SAM3S_H__
#define __SAM3S_H__

/*
 * ==========================================================================
 * ------------------------ CMSIS File Section ------------------------------
 * ==========================================================================
 */

#include "AT91SAM3S4.h"                     /* Device Series Header                               */
#include "core_cm3.h"                       /* Cortex-M3 processor and core peripherals           */
#include "system_SAM3S.h"                   /* System Header                                      */


#endif  // __SAM3S_H__
