<HTML>
  <head>
    <title>TCP Socket Status</title>
    <meta http-equiv="refresh" content="5">
    <BODY TEXT=#000000 BGCOLOR=#ccddff LINK=#0000FF VLINK=#0000FF ALINK=#FF0000>
  </head>

  <H2 ALIGN=CENTER>Tcp Socket online Status</H2>
  <center>
  <TABLE BORDER=0 WIDTH=600>
  <TR BGCOLOR=#aaccff>
    <TH WIDTH=14%>Socket</TH>
    <TH WIDTH=20%>State</TH>
    <TH WIDTH=20%>Rem IP</TH>
    <TH WIDTH=16%>Rem Port</TH>
    <TH WIDTH=16%>Loc Port</TH>
    <TH WIDTH=14%>Timer</TH>
  </TR>