/*----------------------------------------------------------------------------
 *      R T L   K e r n e l   E x a m p l e
 *----------------------------------------------------------------------------
 *      Name:    BLINKY.C
 *      Purpose: RTX example program
 *      Rev.:    V3.40
 *----------------------------------------------------------------------------
 *      This code is part of the RealView Run-Time Library.
 *      Copyright (c) 2004-2008 KEIL - An ARM Company. All rights reserved.
 *---------------------------------------------------------------------------*/

#include <RTL.h>
#include <stdio.h>
#include <TMS470R1.h>                   /* TMS470R1 definitions              */
#include <absacc.h>                     /* To enable absolute adressing      */
#include <std_het.h>                    /* TMS470R1 HET definitions          */
#include "HET.h"                        /* Include generated by HET assembly */
#include "LCD.h"

OS_TID t_phaseA;                        /* assigned task id of task: phase_a */
OS_TID t_phaseB;                        /* assigned task id of task: phase_b */
OS_TID t_phaseC;                        /* assigned task id of task: phase_c */
OS_TID t_phaseD;                        /* assigned task id of task: phase_d */
OS_TID t_clock;                         /* assigned task id of task: clock   */
OS_TID t_lcd;                           /* assigned task id of task: lcd     */
OS_TID t_time;                          /* assigned task id of task: time    */

enum LED_ENUM {OFF, ON};

#define LED_0       (1 << 0)
#define LED_1       (1 << 1)
#define LED_2       (1 << 2)
#define LED_3       (1 << 3)
#define LED_4       (1 << 4)
#define LED_5       (1 << 5)
#define LED_6       (1 << 6)
#define LED_7       (1 << 7)

#define LED_DIR_OUT pGIO->GIOE.GIODIR |=  LED_0 | LED_1 | LED_2 | LED_3 |     \
                                          LED_4 | LED_5 | LED_6 | LED_7 ;
#define LEDS_OFF    pGIO->GIOE.GIODIR |=  LED_0 | LED_1 | LED_2 | LED_3 |     \
                                          LED_4 | LED_5 | LED_6 | LED_7 ;

#define LED_A(x)    ((x) ? (pGIO->GIOE.GIODOUT |= LED_0) : (pGIO->GIOE.GIODOUT &= ~LED_0));
#define LED_B(x)    ((x) ? (pGIO->GIOE.GIODOUT |= LED_1) : (pGIO->GIOE.GIODOUT &= ~LED_1));
#define LED_C(x)    ((x) ? (pGIO->GIOE.GIODOUT |= LED_2) : (pGIO->GIOE.GIODOUT &= ~LED_2));
#define LED_D(x)    ((x) ? (pGIO->GIOE.GIODOUT |= LED_3) : (pGIO->GIOE.GIODOUT &= ~LED_3));
#define LED_CLK(x)  ((x) ? (pGIO->GIOE.GIODOUT |= LED_5) : (pGIO->GIOE.GIODOUT &= ~LED_5));

struct time_s {
  unsigned char h;
  unsigned char m;
  unsigned char s;
} current_time;

/* HET RAM start (dependant on MFBAHR4 value in TMS470R1B1M.s)                */
#define HET_RAM     0x40000000

volatile HETPROGRAM0_UN e_HETPROGRAM0_UN __at(HET_RAM);


/*----------------------------------------------------------------------------
 *        Function 'memcopy32' used for copying HET program to HET RAM
 *---------------------------------------------------------------------------*/
void memcopy32 (unsigned int *dest, unsigned int *src, unsigned int size)  {
  size >>= 2;
  while (size--) *dest++ =  *src++;
}

/*----------------------------------------------------------------------------
 *        Function 'signal_func' called from multiple tasks
 *---------------------------------------------------------------------------*/
void signal_func (OS_TID task)  {
  os_evt_set (0x0100, t_clock);          /* send event signal to clock task  */
  os_dly_wait (50);                      /* delay 50 clock ticks             */
  os_evt_set (0x0100, t_clock);          /* send event signal to clock task  */
  os_dly_wait (50);                      /* delay 50 clock ticks             */
  os_evt_set (0x0001, task);             /* send event to task 'task'        */
  os_dly_wait (50);                      /* delay 50 clock ticks             */
}

/*----------------------------------------------------------------------------
 *        Task 1 'phaseA': Phase A output
 *---------------------------------------------------------------------------*/
__task void phaseA (void) {
  for (;;) {
    os_evt_wait_and (0x0001, 0xffff);    /* wait for an event flag 0x0001    */
    LED_A(ON)
    signal_func (t_phaseB);              /* call common signal function      */
    LED_A(OFF)
  }
}

/*----------------------------------------------------------------------------
 *        Task 2 'phaseB': Phase B output
 *---------------------------------------------------------------------------*/
__task void phaseB (void) {
  for (;;) {
    os_evt_wait_and (0x0001, 0xffff);    /* wait for an event flag 0x0001    */
    LED_B(ON)
    signal_func (t_phaseC);              /* call common signal function      */
    LED_B(OFF)
  }
}

/*----------------------------------------------------------------------------
 *        Task 3 'phaseC': Phase C output
 *---------------------------------------------------------------------------*/
__task void phaseC (void) {
  for (;;) {
    os_evt_wait_and (0x0001, 0xffff);    /* wait for an event flag 0x0001    */
    LED_C(ON)
    signal_func (t_phaseD);              /* call common signal function      */
    LED_C(OFF)
  }
}

/*----------------------------------------------------------------------------
 *        Task 4 'phaseD': Phase D output
 *---------------------------------------------------------------------------*/
__task void phaseD (void) {
  for (;;) {
    os_evt_wait_and (0x0001, 0xffff);    /* wait for an event flag 0x0001    */
    LED_D(ON)
    signal_func (t_phaseA);              /* call common signal function      */
    LED_D(OFF)
  }
}

/*----------------------------------------------------------------------------
 *        Task 5 'clock': Signal Clock
 *---------------------------------------------------------------------------*/
__task void clock (void) {
  for (;;) {
    os_evt_wait_and (0x0100, 0xffff);    /* wait for an event flag 0x0100    */
    LED_CLK(ON)
    os_dly_wait (8);                     /* delay 8 clock ticks              */
    LED_CLK(OFF)
  }
}

/*----------------------------------------------------------------------------
 *        Task 6 'time': Time
 *---------------------------------------------------------------------------*/
__task void time (void) {
  for (;;) {
    os_dly_wait (100);                   /* wait for 100 clock ticks = 1 s   */
    if (current_time.s++ > (60-2)) {
      current_time.s = 0;
      if (current_time.m++ > (60-2)) {
        current_time.m = 0;
        if (current_time.h++ > (24-2)) {
          current_time.h = 0;
        }
      }
    }
  }
}

/*----------------------------------------------------------------------------
 *        Task 6 'lcd': LCD Control task
 *---------------------------------------------------------------------------*/
__task void lcd (void) {
  U32 i;
  char  buf[8+1];

  LCD_init ();                           /* Initialize LCD display module    */
  LCD_backlight (1);                     /* Turn the backlight ON            */
  LCD_clear ();
  LCD_print (0, 0, "    RL-ARM      ");
  LCD_print (0, 1, " Kernel example ");
  os_dly_wait (200);
  LCD_print (0, 1, "  www.keil.com  ");
  os_dly_wait (400);
  LCD_clear ();
  LCD_print (0, 0, "      KEIL      ");
  LCD_print (0, 1, " An ARM Company ");
  os_dly_wait (400);
  LCD_backlight (0);                     /* Turn the backlight OFF           */
  LCD_print (0, 0, "RTX running for:");
  for (;;) {
    for (i = 0; i <= 100; i++) {
      sprintf(buf, "%2.2i:%2.2i:%2.2i ", current_time.h, current_time.m, current_time.s);
      LCD_print (0, 1, buf);
      LCD_bargraph (9, 1, 6, i);
      os_dly_wait (5);
    }
  }
}

/*----------------------------------------------------------------------------
 *        Task 7 'init': Initialize
 *---------------------------------------------------------------------------*/
__task void init (void) {

  current_time.h     = 0;                /* Initialize current time to 0     */
  current_time.m     = 0;
  current_time.s     = 0;

  LED_DIR_OUT                            /* Define LED pins as Outputs       */
  LEDS_OFF                               /* Turn all LEDs off                */

  pGIO->GIOPOL1      = 0x00000000;       /* Falling edge trigger on GIOA4 pin*/
  pGIO->GIOPRY1      = (1 << 4);         /* High-priority interrupt          */
  pGIO->GIOA.GIODIR  = 0x00000000;       /* All GIOA pins are inputs         */
  pGIO->GIOFLG1      = 0x000000FF;       /* Clear interrupt flags for GIOA   */
  pGIO->GIOENA1     |= (1 << 4);         /* Enable GIOA4 pin interrupt       */
  pSM->REQMASK      |= (1 << 5);         /* Enable GIOA interrupt            */

  pHET->HETGCR       = 0x00010002;       /* Clock master + ignore suspend    */
  /* Copy HET program from code memory to HET RAM                            */
  memcopy32 ((unsigned int *) &e_HETPROGRAM0_UN, (unsigned int *) HET_INIT0_PST, sizeof(HET_INIT0_PST));
  pHET->HETDCLR      = 0x000000FF;       /* Clear HET0..7                    */
  pHET->HETDIR       = 0x000000FF;       /* Setup HET0..7 as outputs         */
  pHET->HETPRY      |= (1 << 1);         /* Interrupt priority for HET1      */
  pHET->HETPFR       = 0x0000052B;       /* Set prescale factor              */
  pSM->REQMASK      |= (1 << 7);         /* Enable HET interrupt 1           */
  pHET->HETGCR      |= 0x00000001;       /* Start HET                        */

  t_phaseA = os_tsk_create (phaseA, 0);  /* start task phaseA                */
  t_phaseB = os_tsk_create (phaseB, 0);  /* start task phaseB                */
  t_phaseC = os_tsk_create (phaseC, 0);  /* start task phaseC                */
  t_phaseD = os_tsk_create (phaseD, 0);  /* start task phaseD                */
  t_clock  = os_tsk_create (clock,  0);  /* start task clock                 */
  t_lcd    = os_tsk_create (lcd,    0);  /* start task lcd                   */
  t_time   = os_tsk_create (time,   0);  /* start task time                  */
  os_evt_set (0x0001, t_phaseA);         /* send signal event to task phaseA */
  os_tsk_delete_self ();
}

/*----------------------------------------------------------------------------
 *        Main: Initialize and start RTX Kernel
 *---------------------------------------------------------------------------*/

int main (void) {

  os_sys_init (init);                    /* Initialize RTX and start init    */
}

/*----------------------------------------------------------------------------
 * end of file
 *---------------------------------------------------------------------------*/

