/*----------------------------------------------------------------------------
 *      R T L   K e r n e l   E x a m p l e
 *----------------------------------------------------------------------------
 *      Name:    IRQ.C
 *      Purpose: RTX example program interrupt handler functions
 *      Rev.:    V3.20
 *----------------------------------------------------------------------------
 *      This code is part of the RealView Run-Time Library.
 *      Copyright (c) 2004-2008 KEIL - An ARM Company. All rights reserved.
 *---------------------------------------------------------------------------*/

#include <TMS470R1.h>                   /* TMS470R1 definitions               */
#include <std_het.h>                    /* TMS470R1 HET definitions           */
#include "HET.h"                        /* Include generated by HET assembly  */

#define LED_6       (1 << 6)
#define LED_7       (1 << 7)


__irq void GPIOA_IRQHandler (void) {

  pGIO->GIOE.GIODOUT ^= LED_6;          /* Toggle LED6 if B1 pressed          */

  pGIO->GIOFLG1 = (1 << 4);             /* Clear interrupt flag for GIOA4     */
  pSM->INTREQ  &=~(1 << 5);             /* Clear pending interrupt flag       */
}


__irq void HET_IRQHandler (void) {

  static unsigned int pwm;

  pwm += 100;
  if (pwm > 10000) pwm = 100;

  /* Edit HET_pwm_a_clear data_word value                                     */
  HET_pwm_a_clear_0.memory.data_word = pwm;
  /* Edit HET_pwm_a_det   data_word value                                     */
  HET_pwm_a_set_0.memory.data_word   = 10100-pwm;

  pHET->HETFLG  = (1 << 1);             /* Clear interrupt flag register      */
  pSM->INTREQ  &=~(1 << 7);             /* Clear pending interrupt flag       */
}
