/******************************************************************************/
/*  This file is part of the uVision/ARM development tools                    */
/*  Copyright KEIL ELEKTRONIK GmbH 2002-2009                                  */
/******************************************************************************/
/*                                                                            */
/*  PC72xx.h: Header file for Socle PC72xx Device Series                      */
/*                                                                            */
/******************************************************************************/

#ifndef __PC72xx_H
#define __PC72xx_H

#define inline     __inline

#define SYS_CPU_LITTLE

#include "diag_config.h"
#include "clock.h"
#include "interrupt.h"
#include "dma\dma.h"
#include "platform\PDK_PC72xx\platform.h"
#include "platform\PDK_PC72xx\irqs.h"
#include "platform\PDK_PC72xx\scu.h"
#include "platform\PDK_PC72xx\7230_PS\7230-ps-ctrl.h"
#include "platform\PDK_PC72xx\ADC_PWM\dependency.h"
#include "platform\PDK_PC72xx\ADC_PWM\adc-regs.h"
#include "platform\PDK_PC72xx\ADC_PWM\pwmt-regs.h"
#include "platform\PDK_PC72xx\CACHE\cache.h"
#include "platform\PDK_PC72xx\CACHE\cache-ctrl.h"
#include "platform\PDK_PC72xx\CACHE\cache-regs.h"
#include "platform\PDK_PC72xx\DMA\dependency.h"
#include "platform\PDK_PC72xx\DMA\a2a-regs.h"
#include "platform\PDK_PC72xx\DMA\hdma-regs.h"
#include "platform\PDK_PC72xx\DMA\panther7-hdma-regs.h"
#include "platform\PDK_PC72xx\EHCI\ehcireg.h"
#include "platform\PDK_PC72xx\EHCI\ehcictrl.h"
#include "platform\PDK_PC72xx\EHCI\ehcimem.h"
#include "platform\PDK_PC72xx\GPIO\dependency.h"
#include "platform\PDK_PC72xx\GPIO\gpio-regs.h"
#include "platform\PDK_PC72xx\GPIO\gpio.h"
#include "platform\PDK_PC72xx\I2C\dependency.h"
#include "platform\PDK_PC72xx\I2C\i2c-regs.h"
#include "platform\PDK_PC72xx\I2C\i2c.h"
#include "platform\PDK_PC72xx\I2C\CH700X.h"
#include "platform\PDK_PC72xx\I2C\TVP5145.h"
#include "platform\PDK_PC72xx\I2S\dependency.h"
#include "platform\PDK_PC72xx\I2S\i2s-regs.h"
#include "platform\PDK_PC72xx\I2S\i2s-ctrl.h"
#include "platform\PDK_PC72xx\I2S\codec-ctrl.h"
#include "platform\PDK_PC72xx\I2S\ms6335.h"
#include "platform\PDK_PC72xx\I2S\uda1342ts.h"
#include "platform\PDK_PC72xx\Interrupt\interrupt.h"
#include "platform\PDK_PC72xx\Interrupt\interrupt-regs.h"
#include "platform\PDK_PC72xx\Interrupt\regs-interrupt.h"
#include "platform\PDK_PC72xx\LCD\dependency.h"
#include "platform\PDK_PC72xx\LCD\regs-lcd.h"
#include "platform\PDK_PC72xx\LCD\lcd-ctrl.h"
#include "platform\PDK_PC72xx\LCD\ampire-panel.h"
#include "platform\PDK_PC72xx\MAC\macctrl.h"
#include "platform\PDK_PC72xx\MAC\if_socle.h"
#include "platform\PDK_PC72xx\MAC\gMAC.h"
#include "platform\PDK_PC72xx\MAC\sMACdev.h"
#include "platform\PDK_PC72xx\MAC\macif.h"
#include "platform\PDK_PC72xx\MAC\EEP25x.h"
#include "platform\PDK_PC72xx\MEM\dependency.h"
#include "platform\PDK_PC72xx\MEM\memctrl-regs.h"
#include "platform\PDK_PC72xx\MEM\mem-ctrl.h"
#include "platform\PDK_PC72xx\NAND\dependency.h"
#include "platform\PDK_PC72xx\NAND\nand-flsh-regs.h"
#include "platform\PDK_PC72xx\NAND\rscode-1.0_socle\ecc.h"
#include "platform\PDK_PC72xx\NOR-MXIC\nor-mxic-regs.h"
#include "platform\PDK_PC72xx\NOR-MXIC\nor-mxic-ctrl.h"
#include "platform\PDK_PC72xx\OHCI\ohcireg.h"
#include "platform\PDK_PC72xx\OHCI\ohcictrl.h"
#include "platform\PDK_PC72xx\OHCI\ohcimem.h"
#include "platform\PDK_PC72xx\PANTHER7-HDMA\panther7-hdma-regs.h"
#include "platform\PDK_PC72xx\RTC\rtc-regs.h"
#include "platform\PDK_PC72xx\RTC\rtc-ctrl.h"
#include "platform\PDK_PC72xx\SCU\cdk-scu-regs.h"
#include "platform\PDK_PC72xx\SDMMC\dependency.h"
#include "platform\PDK_PC72xx\SDMMC\sdmmc-regs.h"
#include "platform\PDK_PC72xx\SDMMC\protocol.h"
//#include "platform\PDK_PC72xx\SPI\dependency.h"
#include "platform\PDK_PC72xx\SPI\spi-regs.h"
#include "platform\PDK_PC72xx\SPI\spi-master.h"
#include "platform\PDK_PC72xx\SPI\regs-tsc2000.h"
#include "platform\PDK_PC72xx\SPI\if_gspi.h"
#include "platform\PDK_PC72xx\TIMER\dependency.h"
#include "platform\PDK_PC72xx\TIMER\regs-timer.h"
//#include "platform\PDK_PC72xx\TIMER\timer-regs.h"
#include "platform\PDK_PC72xx\TIMER\timerctrl.h"
#include "platform\PDK_PC72xx\UART\dependency.h"
#include "platform\PDK_PC72xx\UART\uart-regs.h"
#include "platform\PDK_PC72xx\UDC\udcreg.h"
#include "platform\PDK_PC72xx\UDC\usbctrl.h"
#include "platform\PDK_PC72xx\UDC\usbspec.h"
#include "platform\PDK_PC72xx\UDC\usbdescp.h"
#include "platform\PDK_PC72xx\WDT\regs-wdt.h"

#endif /* __PC72xx_H */
