const unsigned char WebSide[] = {
"<html>\r\n"
"<head>\r\n"
"<meta http-equiv=\"refresh\" content=\"1\">\r\n"
"<title>easyWEB - dynamic Webside</title>\r\n"
"</head>\r\n"
"<style type=\"text/css\">\r\n"
"<!--\r\n"
"body {\r\n"
"\r\n"
"    font-family: Tahoma,Arial,Helvetica,Geneva,Swiss,SunSans-Regular;\r\n"
"	font-size: 12px;\r\n"
"}\r\n"
"-->\r\n"
"</style>\r\n"
"\r\n"
"\r\n"
"<body bgcolor=\"#006699\" text=\"#EEEEEE\">\r\n"
"<p><b><font color=\"#FFFFFF\" size=\"6\"><i>STR9 Ethernet</i></font></b></p>\r\n"
"\r\n"
"<table width=100% CELLPADDING=5>\r\n"
"<tr>\r\n"
"<td>\r\n"
"<!---------------------------------------------------------------------------->		   \r\n"
"<!--------------------------------- Buttons ---------------------------------->		   \r\n"
"<!---------------------------------------------------------------------------->		   \r\n"
"\r\n"
"<center><font size=\"+2\"><b>RealTimeClock</b></font><p></center>\r\n"
"<!--------------------------------- Button Up --------------------------------->		   \r\n"
"<b><font size=+1>&nbsp;</font></b></p>\r\n"
"<center><font color=\"CC6600\" size=\"+4\"><b>__:__:__</b></font><p></center>\r\n"
"\r\n"
"\r\n"
"<!---------------------------------------------------------------------------->		   \r\n"
"<!------------------------------- END of Buttons ----------------------------->		   \r\n"
"<!---------------------------------------------------------------------------->		   \r\n"
"\r\n"
"\r\n"
"</td>\r\n"
"\r\n"
"<td VALIGN=TOP>\r\n"
"<p><b>This is a dynamic website hosted by the embedded Webserver</b> <b>easyWEB.</b></p>\r\n"
"<p><b>Hardware:</b></p>\r\n"
"<ul>\r\n"
"<li>Future Electronics Star9 Board</li>\r\n"
"</ul>\r\n"
"<p><b>Software:</b></p>\r\n"
"<ul>\r\n"
"<li>Embedded ENET Ethernet Controller</li>\r\n"
"<li>easyWEB webserver</li>\r\n"
"</ul>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"<p>\r\n"
"<div align=center><font size=-1>Copyright © 2004-2007 KEIL - An ARM Company All rights reserved.</font></div>\r\n"
"</body>\r\n"
"</html>\r\n"
"\r\n"};
